# Use the official Nginx base image
FROM nginx:latest
 
# Copy static website files to the default web root directory
COPY ./static-html /usr/share/nginx/html
 
# Expose the default Nginx port
EXPOSE 80